version: 2.1

orbs:
  python: circleci/python@1.3.2
  # Using windows for builds
  win: circleci/windows@2.4.0
  # Upload artifacts to s3
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  build-connector-win: # Reusable job for basic connectors
    executor:
      name: win/default # comes with python 3.7.3
      shell: cmd.exe
    parameters:
      slug:
        type: string
        default: "arcgis"
      installer:
        type: boolean
        default: false
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Create Innosetup signing cert
          shell: powershell.exe
          command: |
            echo $env:PFX_B64 > "speckle-sharp-ci-tools\SignTool\AEC Systems Ltd.txt"
            certutil -decode "speckle-sharp-ci-tools\SignTool\AEC Systems Ltd.txt" "speckle-sharp-ci-tools\SignTool\AEC Systems Ltd.pfx"
      - run:
          name: Patch
          shell: powershell.exe
          command:
            | # If no tag, use 0.0.0.1 and don't make any YML (for testing only!)
            $tag = if([string]::IsNullOrEmpty($env:CIRCLE_TAG)) { "0.0.0" } else { $env:CIRCLE_TAG }
            $semver = if($tag.Contains('/')) {$tag.Split("/")[1] } else { $tag }
            $ver = if($semver.Contains('-')) {$semver.Split("-")[0] } else { $semver }
            $version = "$($ver).$($env:CIRCLE_BUILD_NUM)"
            echo $semver
            python patch_version.py $semver
            python setup.py sdist bdist_wheel
            Copy-Item -Path "dist\speckle_toolbox-$($ver)-py3-none-any.whl" -Destination "speckle_arcgis_installer"
      - run: 
          name: Build Installer
          shell: cmd.exe
          command:
            | # If no tag, use 0.0.0.1 and don't make any YML (for testing only!)
            speckle-sharp-ci-tools\InnoSetup\ISCC.exe speckle-sharp-ci-tools\arcgis.iss /Sbyparam=$p
      - when:
          condition: << parameters.installer >>
          steps:
            - persist_to_workspace:
                root: ./
                paths:
                  - speckle-sharp-ci-tools/Installers
  publish-github-release:
    docker:
      - image: cimg/base:2021.01
    steps:
      - attach_workspace:
          at: ./speckle_arcgis_installer
      - run:
          name: "Publish Release on GitHub"
          command: |
            mkdir -p ~/git/GitHub/canha
            cd ~/git/GitHub/canha
            git clone https://github.com/canha/golang-tools-install-script 
            cd golang-tools-install-script/
            bash goinstall.sh
            source ~/.bashrc

            go get github.com/tcnksm/ghr
            VERSION=$(my-binary --version)
            $tag = if([string]::IsNullOrEmpty($env:CIRCLE_TAG)) { "0.0.0" } else { $env:CIRCLE_TAG }
            $semver = if($tag.Contains('/')) {$tag.Split("/")[1] } else { $tag }
            $ver = if($semver.Contains('-')) {$semver.Split("-")[0] } else { $semver }
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./speckle_arcgis_installer/speckle_toolbox-$($ver)-py3-none-any.whl

  get-ci-tools: # Clones our ci tools and persists them to the workspace
    docker:
      - image: cimg/base:2021.01
    steps:
      - add_ssh_keys:
          fingerprints:
            - "77:64:03:93:c5:f3:1d:a6:fd:bd:fb:d1:05:56:ca:e9"
      - run:
          name: I know Github as a host
          command: |
            mkdir ~/.ssh
            touch ~/.ssh/known_hosts
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Clone
          command: git clone git@github.com:specklesystems/speckle-sharp-ci-tools.git speckle-sharp-ci-tools
      - persist_to_workspace:
          root: ./
          paths:
            - speckle-sharp-ci-tools

  deploy-manager2:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    parameters:
      slug:
        type: string
      os:
        type: string
      extension:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Install Manager Feed CLI
          command: dotnet tool install --global Speckle.Manager.Feed
      - run:
          name: Upload new version
          command: |
            TAG=$(if [ "${CIRCLE_TAG}" ]; then echo $CIRCLE_TAG; else echo "0.0.0"; fi;)
            SEMVER=$(echo "$TAG" | sed -e 's/\/[a-zA-Z-]*//')
            /root/.dotnet/tools/Speckle.Manager.Feed deploy -s << parameters.slug >> -v ${SEMVER} -u https://releases.speckle.dev/installers/<< parameters.slug >>/<< parameters.slug >>-${SEMVER}.<< parameters.extension >> -o << parameters.os >> -f speckle-sharp-ci-tools/Installers/<< parameters.slug >>/<< parameters.slug >>-${SEMVER}.<< parameters.extension >>
workflows: #happens with every PR to main
  build: # build the installers, but don't persist to workspace for deployment
    jobs:
      - get-ci-tools:
          context: github-dev-bot
          filters:
            branches:
              only:
                - main
                - /ci\/.*/
      - build-connector-win:
          requires:
            - get-ci-tools
          filters:
            branches:
              only:
                - main
                - /ci\/.*/
          context: innosetup

  deploy: # build installers and deploy
    jobs:
      - get-ci-tools:
          context: github-dev-bot
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

      - build-connector-win:
          name: build-deploy-connector-win
          slug: arcgis
          installer: true
          requires:
            - get-ci-tools
          filters:
            tags:
              only: /([0-9]+)\.([0-9]+)\.([0-9]+)(?:-\w+)?$/
            branches:
              ignore: /.*/
          context: innosetup
      - deploy-manager2:
          slug: arcgis
          os: Win
          extension: exe
          requires:
            - build-deploy-connector-win
          filters:
            tags:
              only: /([0-9]+)\.([0-9]+)\.([0-9]+)(?:-\w+)?$/
            branches:
              ignore: /.*/ # For testing only! /ci\/.*/
          context: do-spaces-speckle-releases